/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Update4PatchNotesRouteImport } from './routes/update-4-patch-notes'
import { Route as TranscendentSeedsGuideRouteImport } from './routes/transcendent-seeds-guide'
import { Route as TierListRouteImport } from './routes/tier-list'
import { Route as SeedsDatabaseRouteImport } from './routes/seeds-database'
import { Route as ProfitCalculatorRouteImport } from './routes/profit-calculator'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PetsTierListRouteImport } from './routes/pets-tier-list'
import { Route as MutationsTierListRouteImport } from './routes/mutations-tier-list'
import { Route as MoneyGuideRouteImport } from './routes/money-guide'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EventsGuideRouteImport } from './routes/events-guide'
import { Route as ContractsGuideRouteImport } from './routes/contracts-guide'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompostMachineGuideRouteImport } from './routes/compost-machine-guide'
import { Route as CodesRouteImport } from './routes/codes'
import { Route as BeginnerGuideRouteImport } from './routes/beginner-guide'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const Update4PatchNotesRoute = Update4PatchNotesRouteImport.update({
  id: '/update-4-patch-notes',
  path: '/update-4-patch-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const TranscendentSeedsGuideRoute = TranscendentSeedsGuideRouteImport.update({
  id: '/transcendent-seeds-guide',
  path: '/transcendent-seeds-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const TierListRoute = TierListRouteImport.update({
  id: '/tier-list',
  path: '/tier-list',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedsDatabaseRoute = SeedsDatabaseRouteImport.update({
  id: '/seeds-database',
  path: '/seeds-database',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfitCalculatorRoute = ProfitCalculatorRouteImport.update({
  id: '/profit-calculator',
  path: '/profit-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsTierListRoute = PetsTierListRouteImport.update({
  id: '/pets-tier-list',
  path: '/pets-tier-list',
  getParentRoute: () => rootRouteImport,
} as any)
const MutationsTierListRoute = MutationsTierListRouteImport.update({
  id: '/mutations-tier-list',
  path: '/mutations-tier-list',
  getParentRoute: () => rootRouteImport,
} as any)
const MoneyGuideRoute = MoneyGuideRouteImport.update({
  id: '/money-guide',
  path: '/money-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsGuideRoute = EventsGuideRouteImport.update({
  id: '/events-guide',
  path: '/events-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsGuideRoute = ContractsGuideRouteImport.update({
  id: '/contracts-guide',
  path: '/contracts-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompostMachineGuideRoute = CompostMachineGuideRouteImport.update({
  id: '/compost-machine-guide',
  path: '/compost-machine-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const CodesRoute = CodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => rootRouteImport,
} as any)
const BeginnerGuideRoute = BeginnerGuideRouteImport.update({
  id: '/beginner-guide',
  path: '/beginner-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/beginner-guide': typeof BeginnerGuideRoute
  '/codes': typeof CodesRoute
  '/compost-machine-guide': typeof CompostMachineGuideRoute
  '/contact': typeof ContactRoute
  '/contracts-guide': typeof ContractsGuideRoute
  '/events-guide': typeof EventsGuideRoute
  '/faq': typeof FaqRoute
  '/money-guide': typeof MoneyGuideRoute
  '/mutations-tier-list': typeof MutationsTierListRoute
  '/pets-tier-list': typeof PetsTierListRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profit-calculator': typeof ProfitCalculatorRoute
  '/seeds-database': typeof SeedsDatabaseRoute
  '/tier-list': typeof TierListRoute
  '/transcendent-seeds-guide': typeof TranscendentSeedsGuideRoute
  '/update-4-patch-notes': typeof Update4PatchNotesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/beginner-guide': typeof BeginnerGuideRoute
  '/codes': typeof CodesRoute
  '/compost-machine-guide': typeof CompostMachineGuideRoute
  '/contact': typeof ContactRoute
  '/contracts-guide': typeof ContractsGuideRoute
  '/events-guide': typeof EventsGuideRoute
  '/faq': typeof FaqRoute
  '/money-guide': typeof MoneyGuideRoute
  '/mutations-tier-list': typeof MutationsTierListRoute
  '/pets-tier-list': typeof PetsTierListRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profit-calculator': typeof ProfitCalculatorRoute
  '/seeds-database': typeof SeedsDatabaseRoute
  '/tier-list': typeof TierListRoute
  '/transcendent-seeds-guide': typeof TranscendentSeedsGuideRoute
  '/update-4-patch-notes': typeof Update4PatchNotesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/beginner-guide': typeof BeginnerGuideRoute
  '/codes': typeof CodesRoute
  '/compost-machine-guide': typeof CompostMachineGuideRoute
  '/contact': typeof ContactRoute
  '/contracts-guide': typeof ContractsGuideRoute
  '/events-guide': typeof EventsGuideRoute
  '/faq': typeof FaqRoute
  '/money-guide': typeof MoneyGuideRoute
  '/mutations-tier-list': typeof MutationsTierListRoute
  '/pets-tier-list': typeof PetsTierListRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profit-calculator': typeof ProfitCalculatorRoute
  '/seeds-database': typeof SeedsDatabaseRoute
  '/tier-list': typeof TierListRoute
  '/transcendent-seeds-guide': typeof TranscendentSeedsGuideRoute
  '/update-4-patch-notes': typeof Update4PatchNotesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/beginner-guide'
    | '/codes'
    | '/compost-machine-guide'
    | '/contact'
    | '/contracts-guide'
    | '/events-guide'
    | '/faq'
    | '/money-guide'
    | '/mutations-tier-list'
    | '/pets-tier-list'
    | '/privacy-policy'
    | '/profit-calculator'
    | '/seeds-database'
    | '/tier-list'
    | '/transcendent-seeds-guide'
    | '/update-4-patch-notes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/beginner-guide'
    | '/codes'
    | '/compost-machine-guide'
    | '/contact'
    | '/contracts-guide'
    | '/events-guide'
    | '/faq'
    | '/money-guide'
    | '/mutations-tier-list'
    | '/pets-tier-list'
    | '/privacy-policy'
    | '/profit-calculator'
    | '/seeds-database'
    | '/tier-list'
    | '/transcendent-seeds-guide'
    | '/update-4-patch-notes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/beginner-guide'
    | '/codes'
    | '/compost-machine-guide'
    | '/contact'
    | '/contracts-guide'
    | '/events-guide'
    | '/faq'
    | '/money-guide'
    | '/mutations-tier-list'
    | '/pets-tier-list'
    | '/privacy-policy'
    | '/profit-calculator'
    | '/seeds-database'
    | '/tier-list'
    | '/transcendent-seeds-guide'
    | '/update-4-patch-notes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BeginnerGuideRoute: typeof BeginnerGuideRoute
  CodesRoute: typeof CodesRoute
  CompostMachineGuideRoute: typeof CompostMachineGuideRoute
  ContactRoute: typeof ContactRoute
  ContractsGuideRoute: typeof ContractsGuideRoute
  EventsGuideRoute: typeof EventsGuideRoute
  FaqRoute: typeof FaqRoute
  MoneyGuideRoute: typeof MoneyGuideRoute
  MutationsTierListRoute: typeof MutationsTierListRoute
  PetsTierListRoute: typeof PetsTierListRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProfitCalculatorRoute: typeof ProfitCalculatorRoute
  SeedsDatabaseRoute: typeof SeedsDatabaseRoute
  TierListRoute: typeof TierListRoute
  TranscendentSeedsGuideRoute: typeof TranscendentSeedsGuideRoute
  Update4PatchNotesRoute: typeof Update4PatchNotesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update-4-patch-notes': {
      id: '/update-4-patch-notes'
      path: '/update-4-patch-notes'
      fullPath: '/update-4-patch-notes'
      preLoaderRoute: typeof Update4PatchNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transcendent-seeds-guide': {
      id: '/transcendent-seeds-guide'
      path: '/transcendent-seeds-guide'
      fullPath: '/transcendent-seeds-guide'
      preLoaderRoute: typeof TranscendentSeedsGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tier-list': {
      id: '/tier-list'
      path: '/tier-list'
      fullPath: '/tier-list'
      preLoaderRoute: typeof TierListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeds-database': {
      id: '/seeds-database'
      path: '/seeds-database'
      fullPath: '/seeds-database'
      preLoaderRoute: typeof SeedsDatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profit-calculator': {
      id: '/profit-calculator'
      path: '/profit-calculator'
      fullPath: '/profit-calculator'
      preLoaderRoute: typeof ProfitCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets-tier-list': {
      id: '/pets-tier-list'
      path: '/pets-tier-list'
      fullPath: '/pets-tier-list'
      preLoaderRoute: typeof PetsTierListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mutations-tier-list': {
      id: '/mutations-tier-list'
      path: '/mutations-tier-list'
      fullPath: '/mutations-tier-list'
      preLoaderRoute: typeof MutationsTierListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/money-guide': {
      id: '/money-guide'
      path: '/money-guide'
      fullPath: '/money-guide'
      preLoaderRoute: typeof MoneyGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events-guide': {
      id: '/events-guide'
      path: '/events-guide'
      fullPath: '/events-guide'
      preLoaderRoute: typeof EventsGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts-guide': {
      id: '/contracts-guide'
      path: '/contracts-guide'
      fullPath: '/contracts-guide'
      preLoaderRoute: typeof ContractsGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compost-machine-guide': {
      id: '/compost-machine-guide'
      path: '/compost-machine-guide'
      fullPath: '/compost-machine-guide'
      preLoaderRoute: typeof CompostMachineGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codes': {
      id: '/codes'
      path: '/codes'
      fullPath: '/codes'
      preLoaderRoute: typeof CodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beginner-guide': {
      id: '/beginner-guide'
      path: '/beginner-guide'
      fullPath: '/beginner-guide'
      preLoaderRoute: typeof BeginnerGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BeginnerGuideRoute: BeginnerGuideRoute,
  CodesRoute: CodesRoute,
  CompostMachineGuideRoute: CompostMachineGuideRoute,
  ContactRoute: ContactRoute,
  ContractsGuideRoute: ContractsGuideRoute,
  EventsGuideRoute: EventsGuideRoute,
  FaqRoute: FaqRoute,
  MoneyGuideRoute: MoneyGuideRoute,
  MutationsTierListRoute: MutationsTierListRoute,
  PetsTierListRoute: PetsTierListRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProfitCalculatorRoute: ProfitCalculatorRoute,
  SeedsDatabaseRoute: SeedsDatabaseRoute,
  TierListRoute: TierListRoute,
  TranscendentSeedsGuideRoute: TranscendentSeedsGuideRoute,
  Update4PatchNotesRoute: Update4PatchNotesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
